# Generated by Django 6.0.4 on 2026-04-22 03:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('custo_pontos', models.IntegerField()),
                ('categoria', models.CharField(choices=[('academico', 'Académico'), ('tecnologia', 'Tecnologia'), ('premios', 'Prémios'), ('eventos', 'Eventos')], max_length=20)),
                ('disponivel', models.BooleanField(default=True)),
                ('estoque', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo', models.CharField(choices=[('aluno', 'Aluno'), ('professor', 'Professor'), ('diretor_turma', 'Diretor de Turma'), ('coordenador', 'Coordenador de Atividades'), ('admin', 'Administrador')], default='aluno', max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('is_professor', models.BooleanField(default=False)),
                ('is_coordenador', models.BooleanField(default=False)),
                ('is_diretor_turma', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='core_usuario_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='core_usuario_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('criterios_avaliacao', models.TextField()),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fim', models.TimeField(blank=True, null=True)),
                ('max_pontos_por_aluno', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interrompe_aula', models.BooleanField(default=False, help_text='Marque se esta atividade interrompe as aulas normais', verbose_name='Interrompe aula?')),
                ('tipo_atividade', models.CharField(choices=[('cultural', 'Cultural'), ('ciencia_tecnologia', 'Ciência e Tecnologia')], default='cultural', max_length=20)),
                ('cursos_associados', models.CharField(blank=True, choices=[('eletronica', 'Eletrónica e Telecomunicações'), ('informatica', 'Informática')], max_length=20, null=True)),
                ('todos_cursos', models.BooleanField(default=False)),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='core.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=20, unique=True)),
                ('saldo_pontos', models.IntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_aluno', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilCoordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_coordenador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResgateBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resgate', models.DateTimeField(auto_now_add=True)),
                ('pontos_gastos', models.IntegerField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('entregue', 'Entregue')], default='pendente', max_length=20)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resgates', to='core.perfilaluno')),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resgates', to='core.beneficio')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('tipo', models.CharField(choices=[('adicao', 'Adição'), ('remocao', 'Remoção'), ('distribuicao', 'Distribuição'), ('resgate', 'Resgate')], max_length=20)),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='core.perfilaluno')),
                ('atividade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.atividade')),
                ('professor', models.ForeignKey(blank=True, limit_choices_to={'is_professor': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('curso', models.CharField(choices=[('eletronica', 'Eletrónica e Telecomunicações'), ('informatica', 'Informática')], max_length=20)),
                ('ano', models.CharField(max_length=10)),
                ('horario', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'unique_together': {('nome', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='PerfilProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.disciplina')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_professor', to=settings.AUTH_USER_MODEL)),
                ('turmas', models.ManyToManyField(blank=True, related_name='professores', to='core.turma')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilDiretorTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_diretor', to=settings.AUTH_USER_MODEL)),
                ('turma', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diretor', to='core.turma')),
            ],
        ),
        migrations.AddField(
            model_name='perfilaluno',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='core.turma'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='turmas',
            field=models.ManyToManyField(blank=True, related_name='atividades', to='core.turma'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='turma_vinculada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.turma'),
        ),
        migrations.CreateModel(
            name='DisciplinaTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas_relacionadas', to='core.disciplina')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas_relacionadas', to='core.turma')),
            ],
            options={
                'unique_together': {('disciplina', 'turma')},
            },
        ),
    ]
