# Generated by Django 6.0.4 on 2026-04-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='curso',
            field=models.CharField(choices=[('eletronica', 'Eletrónica e Telecomunicações'), ('informatica', 'Informática')], max_length=20),
        ),
    ]
