# Generated by Django 6.0.4 on 2026-04-18 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('custo_pontos', models.IntegerField()),
                ('categoria', models.CharField(choices=[('academico', 'Académico'), ('tecnologia', 'Tecnologia'), ('premios', 'Prêmios'), ('eventos', 'Eventos')], max_length=20)),
                ('disponivel', models.BooleanField(default=True)),
                ('estoque', models.IntegerField(default=-1)),
            ],
        ),
        migrations.AddField(
            model_name='perfilaluno',
            name='documento',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='perfilprofessor',
            name='turmas',
            field=models.ManyToManyField(blank=True, related_name='professores', to='core.turma'),
        ),
        migrations.AddField(
            model_name='turma',
            name='ano_letivo',
            field=models.CharField(default='2025', max_length=9),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email_institucional',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_coordenador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_diretor_turma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='palavra_passe',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='perfilaluno',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='core.turma'),
        ),
        migrations.AlterField(
            model_name='perfildiretorturma',
            name='turma',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diretor', to='core.turma'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('aluno', 'Aluno'), ('professor', 'Professor'), ('diretor_turma', 'Diretor de Turma'), ('coordenador', 'Coordenador de Atividades'), ('admin', 'Administrador')], default='aluno', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together={('nome', 'curso', 'ano_letivo')},
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('ciencia', 'Ciência e Tecnologia'), ('cultura', 'Culturais'), ('desporto', 'Desporto'), ('voluntariado', 'Voluntariado')], max_length=20)),
                ('requisitos', models.TextField()),
                ('pontuacao_total', models.IntegerField(default=0)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('interrompe_aula', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='disponivel', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coordenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.perfilcoordenador')),
            ],
        ),
        migrations.CreateModel(
            name='ResgateBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resgate', models.DateTimeField(auto_now_add=True)),
                ('pontos_gastos', models.IntegerField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resgates', to='core.perfilaluno')),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resgates', to='core.beneficio')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('tipo', models.CharField(choices=[('adicao', 'Adição'), ('remocao', 'Remoção'), ('transferencia', 'Transferência'), ('resgate', 'Resgate'), ('distribuicao', 'Distribuição')], max_length=20)),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='core.perfilaluno')),
                ('diretor_turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.perfildiretorturma')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.perfilprofessor')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('concluida', 'Concluída')], default='pendente', max_length=20)),
                ('pontos_ganhos', models.IntegerField(default=0)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='core.perfilaluno')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='core.atividade')),
            ],
            options={
                'unique_together': {('aluno', 'atividade')},
            },
        ),
    ]
