# Generated by Django 6.0.4 on 2026-07-22 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='curso_coordenado',
            field=models.CharField(blank=True, choices=[('eletronica', 'Eletrónica e Telecomunicações'), ('informatica', 'Informática')], max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_diretor_pedagogico',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('aluno', 'Aluno'), ('professor', 'Professor'), ('diretor_turma', 'Diretor de Turma'), ('coordenador', 'Coordenador de Atividades'), ('diretor_pedagogico', 'Diretor Pedagógico'), ('admin', 'Administrador')], default='aluno', max_length=20),
        ),
        migrations.CreateModel(
            name='SolicitacaoBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno_nome', models.CharField(max_length=150)),
                ('aluno_processo', models.CharField(max_length=20)),
                ('aluno_turma_nome', models.CharField(max_length=20)),
                ('aluno_curso_nome', models.CharField(max_length=50)),
                ('beneficio_nome', models.CharField(max_length=100)),
                ('beneficio_descricao', models.TextField(blank=True)),
                ('voto_diretor_turma', models.CharField(choices=[('pendente', 'Pendente'), ('aceitar', 'Aceitar'), ('recusar', 'Recusar')], default='pendente', max_length=10)),
                ('voto_coordenador', models.CharField(choices=[('pendente', 'Pendente'), ('aceitar', 'Aceitar'), ('recusar', 'Recusar')], default='pendente', max_length=10)),
                ('voto_diretor_pedagogico', models.CharField(choices=[('pendente', 'Pendente'), ('aceitar', 'Aceitar'), ('recusar', 'Recusar')], default='pendente', max_length=10)),
                ('voto_diretor_turma_em', models.DateTimeField(blank=True, null=True)),
                ('voto_coordenador_em', models.DateTimeField(blank=True, null=True)),
                ('voto_diretor_pedagogico_em', models.DateTimeField(blank=True, null=True)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('prazo_final', models.DateTimeField()),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando Análise'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='aguardando', max_length=10)),
                ('decidido_em', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_beneficio', to='core.perfilaluno')),
                ('aprovador_coordenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_como_coordenador', to=settings.AUTH_USER_MODEL)),
                ('aprovador_diretor_pedagogico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_como_diretor_pedagogico', to=settings.AUTH_USER_MODEL)),
                ('aprovador_diretor_turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_como_diretor_turma', to=settings.AUTH_USER_MODEL)),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='core.beneficio')),
            ],
            options={
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
