# Generated by Django 6.0.4 on 2026-04-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='cursos_associados',
            field=models.CharField(blank=True, choices=[('eletronica', 'Eletrónica e Telecomunicações'), ('informatica', 'Informática')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='tipo_atividade',
            field=models.CharField(choices=[('cultural', 'Cultural'), ('ciencia_tecnologia', 'Ciência e Tecnologia')], default='cultural', max_length=20),
        ),
        migrations.AddField(
            model_name='atividade',
            name='todos_cursos',
            field=models.BooleanField(default=False),
        ),
    ]
