# Generated by Django 6.0.4 on 2026-04-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_beneficio_perfilaluno_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='horario',
            field=models.CharField(blank=True, default='Tarde', max_length=20),
        ),
    ]
