# Generated by Django 6.0.4 on 2026-04-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_turma_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='foto',
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_coordenador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_diretor_turma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_professor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='turma_vinculada',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('aluno', 'Aluno'), ('professor', 'Professor'), ('diretor_turma', 'Diretor de Turma'), ('coordenador', 'Coordenador de Atividades'), ('admin', 'Administrador')], default='aluno', max_length=20),
        ),
    ]
