# Generated by Django 6.0.4 on 2026-04-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_turma_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email_institucional',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_coordenador',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_diretor_turma',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='palavra_passe',
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='horario',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
