# Generated by Django 6.0.4 on 2026-04-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_usuario_email_institucional_and_more'),
    ]

    operations = [
    ]
